### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by TheFox** [TheFox/timr#4]
### General

- [x] Remove MVC/TermKit.
- [x] Remove interactive mode. Just commands.
- [x] New README
- [x] README Workflow Example
- [x] rdoc
- [x] man
- [x] Bash Completion

### Task

- [x] Task Command
- [x] Task Add Command
- [x] Task Remove Command
- [x] Task Set Command
- [x] Task Estimation
- [x] Set a Task to `is_billed`. (All Tracks are updated.)
- [x] Flat Rate

### Track

- [x] Track Command
- [x] Track Add Command
- [x] Track Add Start End Dates optional.
- [x] Track Remove Command
- [x] Track Set Command
- [x] Set a Track to `is_billed`. (Filter on log.)

### Misc

- [x] Report Command (+Templates?)
- [x] Report Estimation
- [x] BasicModel Tests
- [x] Move private used mothods to `private`.
- [x] Hash default. Use `hash.fetch(:field, 'default_val')`

### Further Features

- Burndownrate: linear and [Brachistochrone](https://www.youtube.com/watch?v=skvnj67YGmw)?
